const pool = require('../db');

const plants = [
  {
    name: "Monstera Deliciosa",
    price: 599,
    image: "https://images.unsplash.com/photo-1614594975525-e45190c55d0b?w=500",
    category: "Indoor",
    tagline: "The iconic split-leaf beauty",
    description: "Monstera Deliciosa is a stunning tropical plant native to Central America. Known for its dramatic split leaves, it thrives indoors and can grow quite large over time. It purifies air and adds a bold tropical statement to any room. Perfect for bright indirect light spots.",
    sunlight: "Indirect bright light",
    watering: "Once a week",
    temperature: "18°C – 30°C",
    pot_size: "8–10 inch pot",
    difficulty: "Beginner friendly",
    pruning: "Trim yellow leaves monthly",
    humidity: "High (60–80%)",
    pet_safe: "No — toxic to pets",
    rating: 4.8,
    reviews: 1245
  },
  {
    name: "Snake Plant",
    price: 299,
    image: "https://images.unsplash.com/photo-1593691509543-c55fb32d8de5?w=500",
    category: "Air Purifying",
    tagline: "Virtually indestructible air purifier",
    description: "Snake Plant, also known as Sansevieria, is one of the hardiest houseplants available. It thrives on neglect and can survive low light conditions. It releases oxygen at night making it perfect for bedrooms. An ideal plant for beginners.",
    sunlight: "Low to bright indirect light",
    watering: "Once in 2–3 weeks",
    temperature: "15°C – 35°C",
    pot_size: "4–6 inch pot",
    difficulty: "Very easy",
    pruning: "Remove dead leaves",
    humidity: "Low (30–50%)",
    pet_safe: "No — toxic to pets",
    rating: 4.7,
    reviews: 2100
  },
  {
    name: "Peace Lily",
    price: 349,
    image: "https://images.unsplash.com/photo-1599598425947-5202edd56fde?w=500",
    category: "Air Purifying",
    tagline: "Elegant white blooms indoors",
    description: "Peace Lily is a graceful flowering plant that thrives in low light conditions. It produces beautiful white spathes and is excellent at purifying indoor air. It droops when thirsty, making it easy to know when to water.",
    sunlight: "Low to medium indirect light",
    watering: "Once a week",
    temperature: "18°C – 30°C",
    pot_size: "6–8 inch pot",
    difficulty: "Beginner friendly",
    pruning: "Remove spent flowers",
    humidity: "Medium (50–60%)",
    pet_safe: "No — toxic to pets",
    rating: 4.6,
    reviews: 980
  },
  {
    name: "ZZ Plant",
    price: 599,
    image: "https://images.unsplash.com/photo-1632207691143-643e2a9a9361?w=500",
    category: "Indoor",
    tagline: "Glossy leaves, zero fuss",
    description: "ZZ Plant is a drought-tolerant beauty with thick glossy leaves. It stores water in its roots making it perfect for forgetful waterers. It thrives in almost any light condition and is extremely low maintenance.",
    sunlight: "Low to bright indirect light",
    watering: "Once in 2–3 weeks",
    temperature: "15°C – 35°C",
    pot_size: "6–8 inch pot",
    difficulty: "Very easy",
    pruning: "Minimal — remove dead stems",
    humidity: "Low (30–50%)",
    pet_safe: "No — toxic to pets",
    rating: 4.7,
    reviews: 506
  },
  {
    name: "Pothos",
    price: 199,
    image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=500",
    category: "Hanging",
    tagline: "The perfect trailing plant",
    description: "Pothos is one of the most popular and easy-care houseplants. Its trailing vines look gorgeous on shelves or hanging baskets. It tolerates low light and irregular watering, making it ideal for beginners.",
    sunlight: "Low to medium indirect light",
    watering: "Once a week",
    temperature: "15°C – 30°C",
    pot_size: "4–6 inch pot",
    difficulty: "Very easy",
    pruning: "Trim long vines monthly",
    humidity: "Medium (40–60%)",
    pet_safe: "No — toxic to pets",
    rating: 4.8,
    reviews: 3200
  },
  {
    name: "Aloe Vera",
    price: 149,
    image: "https://images.unsplash.com/photo-1567331711402-509c12c41959?w=500",
    category: "Herbs & Medicinal",
    tagline: "Nature's first aid plant",
    description: "Aloe Vera is a succulent plant species famous for its medicinal properties. The gel inside its leaves soothes sunburns and skin irritations. It thrives in bright light with minimal watering.",
    sunlight: "Bright direct or indirect light",
    watering: "Once in 2 weeks",
    temperature: "13°C – 35°C",
    pot_size: "4–6 inch pot",
    difficulty: "Very easy",
    pruning: "Remove outer leaves as needed",
    humidity: "Low (30–40%)",
    pet_safe: "No — toxic to pets",
    rating: 4.9,
    reviews: 4500
  },
  {
    name: "Spider Plant",
    price: 249,
    image: "https://images.unsplash.com/photo-1572688484438-313a6e50c333?w=500",
    category: "Air Purifying",
    tagline: "Fast growing and air purifying",
    description: "Spider Plant is a cheerful, fast-growing houseplant that produces baby plantlets on long stems. It is excellent at removing toxins from the air and thrives in a wide range of conditions.",
    sunlight: "Indirect bright light",
    watering: "Once a week",
    temperature: "13°C – 30°C",
    pot_size: "4–6 inch pot",
    difficulty: "Very easy",
    pruning: "Remove brown tips",
    humidity: "Medium (40–60%)",
    pet_safe: "Yes — safe for pets",
    rating: 4.7,
    reviews: 1800
  },
  {
    name: "Rubber Plant",
    price: 499,
    image: "https://images.unsplash.com/photo-1598880940080-ff9a29891b85?w=500",
    category: "Air Purifying",
    tagline: "Bold leaves, bold statement",
    description: "Rubber Plant features large, glossy dark green leaves and can grow into a stunning indoor tree. It is a great air purifier and adds a dramatic tropical feel to any space.",
    sunlight: "Bright indirect light",
    watering: "Once a week",
    temperature: "15°C – 30°C",
    pot_size: "8–10 inch pot",
    difficulty: "Beginner friendly",
    pruning: "Trim to control height",
    humidity: "Medium (40–60%)",
    pet_safe: "No — toxic to pets",
    rating: 4.6,
    reviews: 760
  },
  {
    name: "Fiddle Leaf Fig",
    price: 899,
    image: "https://images.unsplash.com/photo-1545241047-6083a3684587?w=500",
    category: "Indoor",
    tagline: "The designer's favorite plant",
    description: "Fiddle Leaf Fig is the ultimate statement houseplant with its large violin-shaped leaves. It loves bright indirect light and consistent watering. A must-have for modern interior design.",
    sunlight: "Bright indirect light",
    watering: "Once a week",
    temperature: "16°C – 30°C",
    pot_size: "10–12 inch pot",
    difficulty: "Intermediate",
    pruning: "Trim lower leaves as it grows",
    humidity: "Medium (50–60%)",
    pet_safe: "No — toxic to pets",
    rating: 4.5,
    reviews: 890
  },
  {
    name: "Boston Fern",
    price: 349,
    image: "https://images.unsplash.com/photo-1520412099551-62b6bafeb5bb?w=500",
    category: "Ferns & Foliage",
    tagline: "Lush and feathery elegance",
    description: "Boston Fern is a classic houseplant with graceful arching fronds. It loves humidity and indirect light, making it perfect for bathrooms or kitchens. It is a natural humidifier.",
    sunlight: "Indirect bright light",
    watering: "Keep soil moist",
    temperature: "15°C – 25°C",
    pot_size: "6–8 inch pot",
    difficulty: "Intermediate",
    pruning: "Remove dead fronds regularly",
    humidity: "High (60–80%)",
    pet_safe: "Yes — safe for pets",
    rating: 4.5,
    reviews: 640
  },
  {
    name: "Jade Plant",
    price: 299,
    image: "https://images.unsplash.com/photo-1509423350716-97f9360b4e09?w=500",
    category: "Lucky & Vastu",
    tagline: "Symbol of good luck and prosperity",
    description: "Jade Plant is a long-lived succulent considered a symbol of good fortune. Its thick oval leaves and tree-like structure make it a beautiful desktop plant. It can live for decades with proper care.",
    sunlight: "Bright direct light",
    watering: "Once in 2 weeks",
    temperature: "15°C – 30°C",
    pot_size: "4–6 inch pot",
    difficulty: "Easy",
    pruning: "Pinch tips to encourage bushiness",
    humidity: "Low (30–40%)",
    pet_safe: "No — toxic to pets",
    rating: 4.7,
    reviews: 1100
  },
  {
    name: "Chinese Evergreen",
    price: 399,
    image: "https://images.unsplash.com/photo-1587334274328-64186a80aeee?w=500",
    category: "Air Purifying",
    tagline: "Colourful and ultra low maintenance",
    description: "Chinese Evergreen is one of the most adaptable and decorative houseplants. Available in beautiful shades of green, silver, and red, it tolerates low light and is almost impossible to kill.",
    sunlight: "Low to medium indirect light",
    watering: "Once a week",
    temperature: "16°C – 30°C",
    pot_size: "6–8 inch pot",
    difficulty: "Very easy",
    pruning: "Remove yellow leaves",
    humidity: "Medium (40–60%)",
    pet_safe: "No — toxic to pets",
    rating: 4.6,
    reviews: 720
  },
  {
    name: "Philodendron",
    price: 449,
    image: "https://images.unsplash.com/photo-1612852098516-55d01c75769a?w=500",
    category: "Climbers",
    tagline: "Heart shaped leaves full of love",
    description: "Philodendron is a classic tropical houseplant with heart-shaped glossy leaves. It is a vigorous grower and excellent air purifier. Perfect for hanging baskets or climbing on a moss pole.",
    sunlight: "Medium indirect light",
    watering: "Once a week",
    temperature: "16°C – 30°C",
    pot_size: "6–8 inch pot",
    difficulty: "Beginner friendly",
    pruning: "Trim to control growth",
    humidity: "Medium (50–60%)",
    pet_safe: "No — toxic to pets",
    rating: 4.7,
    reviews: 930
  },
  {
    name: "Calathea",
    price: 549,
    image: "https://images.unsplash.com/photo-1614594975525-e45190c55d0b?w=500",
    category: "Ferns & Foliage",
    tagline: "Living art with patterned leaves",
    description: "Calathea is famous for its stunning patterned leaves in shades of green, purple, and silver. Its leaves move throughout the day following light, earning it the nickname prayer plant.",
    sunlight: "Low to medium indirect light",
    watering: "Twice a week",
    temperature: "18°C – 30°C",
    pot_size: "6–8 inch pot",
    difficulty: "Intermediate",
    pruning: "Remove brown leaf edges",
    humidity: "High (60–80%)",
    pet_safe: "Yes — safe for pets",
    rating: 4.5,
    reviews: 580
  },
  {
    name: "Bird of Paradise",
    price: 1299,
    image: "https://images.unsplash.com/photo-1598880940080-ff9a29891b85?w=500",
    category: "Palms & Tropicals",
    tagline: "Tropical drama at its finest",
    description: "Bird of Paradise is a majestic tropical plant with enormous paddle-shaped leaves. It can grow up to 2 meters indoors and creates an instant tropical paradise in any room.",
    sunlight: "Bright direct or indirect light",
    watering: "Once a week",
    temperature: "18°C – 35°C",
    pot_size: "12–14 inch pot",
    difficulty: "Intermediate",
    pruning: "Remove dead leaves at base",
    humidity: "Medium (50–60%)",
    pet_safe: "No — toxic to pets",
    rating: 4.8,
    reviews: 430
  },
  {
    name: "Dracaena",
    price: 449,
    image: "https://images.unsplash.com/photo-1593691509543-c55fb32d8de5?w=500",
    category: "Air Purifying",
    tagline: "Architectural elegance indoors",
    description: "Dracaena is a striking architectural plant with long strappy leaves often edged in red or yellow. It is one of the best air-purifying plants and extremely tolerant of neglect.",
    sunlight: "Low to bright indirect light",
    watering: "Once in 10 days",
    temperature: "15°C – 30°C",
    pot_size: "6–10 inch pot",
    difficulty: "Easy",
    pruning: "Cut back leggy stems",
    humidity: "Low to medium (40–60%)",
    pet_safe: "No — toxic to pets",
    rating: 4.6,
    reviews: 810
  },
  {
    name: "Cactus Mix",
    price: 199,
    image: "https://images.unsplash.com/photo-1459411621453-7b03977f4bfc?w=500",
    category: "Cactus",
    tagline: "Desert beauty, zero effort",
    description: "A mix of assorted cacti that are virtually indestructible. These sun-loving plants store water in their stems and thrive on neglect. Perfect for sunny windowsills.",
    sunlight: "Bright direct sunlight",
    watering: "Once in 3–4 weeks",
    temperature: "10°C – 40°C",
    pot_size: "3–4 inch pot",
    difficulty: "Very easy",
    pruning: "Not required",
    humidity: "Very low (20–30%)",
    pet_safe: "No — sharp spines",
    rating: 4.7,
    reviews: 2300
  },
  {
    name: "Echeveria",
    price: 249,
    image: "https://images.unsplash.com/photo-1550159930-40066082a4fc?w=500",
    category: "Succulents",
    tagline: "Rosette perfection in a pot",
    description: "Echeveria is a stunning rosette-forming succulent available in dozens of colors. It is perfect for windowsills, terrariums, or as a desk plant. Minimal care required.",
    sunlight: "Bright direct light",
    watering: "Once in 2 weeks",
    temperature: "10°C – 35°C",
    pot_size: "3–4 inch pot",
    difficulty: "Easy",
    pruning: "Remove dead outer leaves",
    humidity: "Low (20–40%)",
    pet_safe: "Yes — safe for pets",
    rating: 4.8,
    reviews: 1650
  },
  {
    name: "Holy Basil (Tulsi)",
    price: 149,
    image: "https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?w=500",
    category: "Herbs & Medicinal",
    tagline: "Sacred herb of Indian homes",
    description: "Tulsi or Holy Basil is one of the most sacred plants in Indian culture. It has powerful medicinal and antibacterial properties. The leaves are used in teas, medicines, and religious ceremonies.",
    sunlight: "Full sunlight",
    watering: "Daily",
    temperature: "20°C – 35°C",
    pot_size: "6–8 inch pot",
    difficulty: "Easy",
    pruning: "Pinch flower buds regularly",
    humidity: "Medium (50–60%)",
    pet_safe: "Yes — safe for pets",
    rating: 4.9,
    reviews: 3800
  },
  {
    name: "Neem",
    price: 199,
    image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=500",
    category: "Herbs & Medicinal",
    tagline: "Nature's pharmacy in a tree",
    description: "Neem tree is one of the most valuable medicinal trees known to mankind. Every part of the tree has medicinal uses. It is a natural insect repellent and air purifier.",
    sunlight: "Full sunlight",
    watering: "Twice a week",
    temperature: "20°C – 40°C",
    pot_size: "10–12 inch pot",
    difficulty: "Easy",
    pruning: "Annual pruning recommended",
    humidity: "Low to medium (40–50%)",
    pet_safe: "No — toxic to pets",
    rating: 4.7,
    reviews: 920
  },
  {
    name: "Lavender",
    price: 349,
    image: "https://images.unsplash.com/photo-1499028344343-cd173ffc68a9?w=500",
    category: "Flowering",
    tagline: "Purple fragrance for your garden",
    description: "Lavender is a fragrant herb beloved for its beautiful purple flowers and calming scent. It attracts pollinators and repels mosquitoes naturally. Perfect for balconies and garden borders.",
    sunlight: "Full direct sunlight",
    watering: "Once a week",
    temperature: "15°C – 30°C",
    pot_size: "6–8 inch pot",
    difficulty: "Easy",
    pruning: "Trim after flowering",
    humidity: "Low (30–40%)",
    pet_safe: "No — toxic to pets",
    rating: 4.8,
    reviews: 1420
  },
  {
    name: "Hibiscus",
    price: 299,
    image: "https://images.unsplash.com/photo-1508193638397-1c4234db14d8?w=500",
    category: "Flowering",
    tagline: "Vibrant tropical blooms daily",
    description: "Hibiscus produces stunning large flowers in red, pink, yellow, and orange. It blooms almost year round in Indian climates. The flowers are used in teas and hair oils.",
    sunlight: "Full direct sunlight",
    watering: "Daily",
    temperature: "20°C – 35°C",
    pot_size: "10–12 inch pot",
    difficulty: "Easy",
    pruning: "Prune after each bloom cycle",
    humidity: "Medium (50–60%)",
    pet_safe: "Yes — safe for pets",
    rating: 4.7,
    reviews: 1890
  },
  {
    name: "Bougainvillea",
    price: 399,
    image: "https://images.unsplash.com/photo-1444930694458-01babf71870c?w=500",
    category: "Flowering",
    tagline: "A riot of colour all year",
    description: "Bougainvillea is a spectacular flowering vine known for its vibrant paper-like bracts in shades of pink, red, orange, and purple. It thrives in hot sunny conditions and blooms profusely.",
    sunlight: "Full direct sunlight",
    watering: "Twice a week",
    temperature: "20°C – 40°C",
    pot_size: "12–14 inch pot",
    difficulty: "Easy",
    pruning: "Prune after flowering",
    humidity: "Low to medium (40–50%)",
    pet_safe: "No — thorns present",
    rating: 4.8,
    reviews: 2100
  },
  {
    name: "Croton",
    price: 349,
    image: "https://images.unsplash.com/photo-1587334274328-64186a80aeee?w=500",
    category: "Outdoor",
    tagline: "Nature's most colorful foliage",
    description: "Croton is a stunning foliage plant with leaves in brilliant shades of red, orange, yellow, and green. It loves bright light and adds a tropical explosion of colour to gardens and balconies.",
    sunlight: "Bright direct or indirect light",
    watering: "Twice a week",
    temperature: "18°C – 35°C",
    pot_size: "8–10 inch pot",
    difficulty: "Easy",
    pruning: "Pinch tips for bushiness",
    humidity: "Medium (50–60%)",
    pet_safe: "No — toxic to pets",
    rating: 4.6,
    reviews: 780
  },
  {
    name: "Areca Palm",
    price: 799,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500",
    category: "Palms & Tropicals",
    tagline: "Bring the tropics indoors",
    description: "Areca Palm is one of the most popular indoor palms, known for its feathery arching fronds. It is a natural humidifier and one of the best air purifying plants according to NASA.",
    sunlight: "Bright indirect light",
    watering: "Twice a week",
    temperature: "16°C – 35°C",
    pot_size: "10–12 inch pot",
    difficulty: "Easy",
    pruning: "Remove yellow fronds",
    humidity: "Medium to high (50–70%)",
    pet_safe: "Yes — safe for pets",
    rating: 4.7,
    reviews: 1340
  },
  {
    name: "Money Plant",
    price: 149,
    image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=500",
    category: "Lucky & Vastu",
    tagline: "Good luck in every leaf",
    description: "Money Plant is one of the most popular houseplants in India, believed to bring good luck and prosperity. It is extremely easy to grow in water or soil and purifies indoor air effectively.",
    sunlight: "Low to bright indirect light",
    watering: "Once a week",
    temperature: "15°C – 35°C",
    pot_size: "4–6 inch pot",
    difficulty: "Very easy",
    pruning: "Trim long vines",
    humidity: "Low to medium (40–60%)",
    pet_safe: "No — toxic to pets",
    rating: 4.9,
    reviews: 5200
  },
  {
    name: "Bamboo Plant",
    price: 499,
    image: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=500",
    category: "Lucky & Vastu",
    tagline: "Lucky bamboo for positive energy",
    description: "Lucky Bamboo is a popular Feng Shui plant believed to bring good luck and positive energy. It grows beautifully in water or soil and requires minimal care.",
    sunlight: "Low to medium indirect light",
    watering: "Change water every 2 weeks",
    temperature: "15°C – 35°C",
    pot_size: "4–6 inch pot",
    difficulty: "Very easy",
    pruning: "Trim yellow leaves",
    humidity: "Medium (50–60%)",
    pet_safe: "No — toxic to pets",
    rating: 4.8,
    reviews: 2800
  },
  {
    name: "Anthurium",
    price: 649,
    image: "https://images.unsplash.com/photo-1599598425947-5202edd56fde?w=500",
    category: "Flowering",
    tagline: "Waxy blooms that last for months",
    description: "Anthurium produces stunning glossy heart-shaped flowers in red, pink, and white that can last for months. It is a low maintenance flowering plant that blooms almost year round indoors.",
    sunlight: "Bright indirect light",
    watering: "Once a week",
    temperature: "18°C – 30°C",
    pot_size: "6–8 inch pot",
    difficulty: "Easy",
    pruning: "Remove spent flowers",
    humidity: "High (60–80%)",
    pet_safe: "No — toxic to pets",
    rating: 4.7,
    reviews: 960
  },
  {
    name: "String of Pearls",
    price: 449,
    image: "https://images.unsplash.com/photo-1550159930-40066082a4fc?w=500",
    category: "Hanging",
    tagline: "A cascading necklace of green",
    description: "String of Pearls is a unique trailing succulent with round bead-like leaves that cascade beautifully from hanging pots. It is a conversation starter and requires very little care.",
    sunlight: "Bright indirect light",
    watering: "Once in 2 weeks",
    temperature: "15°C – 30°C",
    pot_size: "4–6 inch pot",
    difficulty: "Intermediate",
    pruning: "Trim dead strands",
    humidity: "Low (30–40%)",
    pet_safe: "No — toxic to pets",
    rating: 4.6,
    reviews: 720
  },
  {
    name: "Haworthia",
    price: 299,
    image: "https://images.unsplash.com/photo-1459411621453-7b03977f4bfc?w=500",
    category: "Succulents",
    tagline: "Tiny but mighty succulent",
    description: "Haworthia is a compact succulent with attractive white striped leaves. It is perfect for small spaces and terrariums. Unlike most succulents it prefers shade making it ideal for indoor growing.",
    sunlight: "Low to medium indirect light",
    watering: "Once in 2–3 weeks",
    temperature: "10°C – 35°C",
    pot_size: "3–4 inch pot",
    difficulty: "Very easy",
    pruning: "Remove dead outer leaves",
    humidity: "Low (30–40%)",
    pet_safe: "Yes — safe for pets",
    rating: 4.7,
    reviews: 890
  },
  {
    name: "Rosemary",
    price: 249,
    image: "https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?w=500",
    category: "Herbs & Medicinal",
    tagline: "Herb of memory and fragrance",
    description: "Rosemary is a fragrant woody herb used extensively in cooking and aromatherapy. It improves memory and concentration when its scent is inhaled. Grows beautifully in pots on sunny balconies.",
    sunlight: "Full direct sunlight",
    watering: "Once a week",
    temperature: "15°C – 30°C",
    pot_size: "6–8 inch pot",
    difficulty: "Easy",
    pruning: "Trim regularly for bushiness",
    humidity: "Low (30–40%)",
    pet_safe: "Yes — safe for pets",
    rating: 4.7,
    reviews: 1100
  },
  {
    name: "Mint",
    price: 99,
    image: "https://images.unsplash.com/photo-1628556270448-4d4e4148e1b1?w=500",
    category: "Herbs & Medicinal",
    tagline: "Fresh flavour at your fingertips",
    description: "Mint is a fast-growing aromatic herb perfect for kitchen gardens. Its leaves are used in chutneys, teas, and cocktails. It spreads quickly and loves moist soil.",
    sunlight: "Partial to full sunlight",
    watering: "Daily",
    temperature: "15°C – 30°C",
    pot_size: "6–8 inch pot",
    difficulty: "Very easy",
    pruning: "Harvest regularly to prevent flowering",
    humidity: "Medium (50–60%)",
    pet_safe: "No — toxic to pets in large amounts",
    rating: 4.8,
    reviews: 4100
  },
  {
    name: "Coriander",
    price: 79,
    image: "https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?w=500",
    category: "Herbs & Medicinal",
    tagline: "Fresh greens from your own pot",
    description: "Coriander or Dhania is an essential herb in Indian cooking. Growing your own ensures fresh fragrant leaves always at hand. It grows quickly from seeds and loves cool weather.",
    sunlight: "Partial sunlight",
    watering: "Daily",
    temperature: "15°C – 25°C",
    pot_size: "6–8 inch pot",
    difficulty: "Easy",
    pruning: "Harvest outer leaves regularly",
    humidity: "Medium (50–60%)",
    pet_safe: "Yes — safe for pets",
    rating: 4.6,
    reviews: 2900
  },
  {
    name: "Curry Leaf Plant",
    price: 199,
    image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=500",
    category: "Herbs & Medicinal",
    tagline: "Essential flavour of Indian cooking",
    description: "Curry Leaf plant is an essential in every Indian kitchen garden. Fresh curry leaves have an intense aroma and flavour far superior to dried ones. It is a fast grower in warm climates.",
    sunlight: "Full direct sunlight",
    watering: "Twice a week",
    temperature: "20°C – 40°C",
    pot_size: "8–10 inch pot",
    difficulty: "Easy",
    pruning: "Harvest regularly",
    humidity: "Medium (50–60%)",
    pet_safe: "Yes — safe for pets",
    rating: 4.9,
    reviews: 3600
  },
  {
    name: "Adenium (Desert Rose)",
    price: 699,
    image: "https://images.unsplash.com/photo-1508193638397-1c4234db14d8?w=500",
    category: "Flowering",
    tagline: "Stunning bonsai-like flowering plant",
    description: "Adenium or Desert Rose is a striking succulent shrub with a swollen trunk and gorgeous trumpet-shaped flowers. It looks like a miniature bonsai and blooms profusely in hot weather.",
    sunlight: "Full direct sunlight",
    watering: "Once a week",
    temperature: "20°C – 40°C",
    pot_size: "8–10 inch pot",
    difficulty: "Easy",
    pruning: "Prune after flowering",
    humidity: "Low (30–40%)",
    pet_safe: "No — toxic to pets",
    rating: 4.8,
    reviews: 870
  },
  {
    name: "Ficus Bonsai",
    price: 1499,
    image: "https://images.unsplash.com/photo-1599598425947-5202edd56fde?w=500",
    category: "Bonsai",
    tagline: "Ancient art of miniature trees",
    description: "Ficus Bonsai is a beautifully trained miniature tree that brings Zen energy to any space. With proper pruning and care it develops a stunning aged trunk and canopy over time.",
    sunlight: "Bright indirect light",
    watering: "Every 2–3 days",
    temperature: "15°C – 30°C",
    pot_size: "Bonsai tray",
    difficulty: "Advanced",
    pruning: "Regular shaping required",
    humidity: "Medium (50–60%)",
    pet_safe: "No — toxic to pets",
    rating: 4.9,
    reviews: 340
  },
  {
    name: "Schefflera",
    price: 549,
    image: "https://images.unsplash.com/photo-1587334274328-64186a80aeee?w=500",
    category: "Indoor",
    tagline: "Umbrella plant for instant greenery",
    description: "Schefflera or Umbrella Plant has attractive glossy leaves arranged in a circular pattern resembling an umbrella. It is a fast grower and excellent air purifier for large indoor spaces.",
    sunlight: "Bright indirect light",
    watering: "Once a week",
    temperature: "15°C – 30°C",
    pot_size: "8–10 inch pot",
    difficulty: "Easy",
    pruning: "Trim to control height",
    humidity: "Medium (50–60%)",
    pet_safe: "No — toxic to pets",
    rating: 4.5,
    reviews: 560
  },
  {
    name: "Oxalis (Purple Shamrock)",
    price: 299,
    image: "https://images.unsplash.com/photo-1612852098516-55d01c75769a?w=500",
    category: "Indoor",
    tagline: "Dancing purple butterflies in a pot",
    description: "Oxalis triangularis or Purple Shamrock has stunning triangular purple leaves that fold up at night like butterflies going to sleep. It produces delicate pink flowers and is a true conversation piece.",
    sunlight: "Bright indirect light",
    watering: "Once a week",
    temperature: "15°C – 25°C",
    pot_size: "4–6 inch pot",
    difficulty: "Easy",
    pruning: "Remove dead leaves",
    humidity: "Medium (40–60%)",
    pet_safe: "No — toxic to pets",
    rating: 4.7,
    reviews: 430
  },
  {
    name: "Tradescantia",
    price: 249,
    image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=500",
    category: "Hanging",
    tagline: "Purple and green trailing beauty",
    description: "Tradescantia or Spiderwort is a fast-growing trailing plant with striking purple and green striped leaves. It is incredibly easy to propagate and maintain, making it perfect for beginners.",
    sunlight: "Medium to bright indirect light",
    watering: "Once a week",
    temperature: "15°C – 30°C",
    pot_size: "4–6 inch pot",
    difficulty: "Very easy",
    pruning: "Pinch tips for bushiness",
    humidity: "Medium (40–60%)",
    pet_safe: "No — skin irritant",
    rating: 4.6,
    reviews: 680
  },
  {
    name: "Hoya",
    price: 499,
    image: "https://images.unsplash.com/photo-1614594975525-e45190c55d0b?w=500",
    category: "Climbers",
    tagline: "Waxy leaves and star shaped blooms",
    description: "Hoya or Wax Plant produces clusters of stunning star-shaped fragrant flowers. Its thick waxy leaves store water making it drought tolerant. A collector's favourite with hundreds of varieties.",
    sunlight: "Bright indirect light",
    watering: "Once in 10 days",
    temperature: "16°C – 30°C",
    pot_size: "4–6 inch pot",
    difficulty: "Easy",
    pruning: "Do not remove flower spurs",
    humidity: "Medium (50–60%)",
    pet_safe: "Yes — safe for pets",
    rating: 4.8,
    reviews: 790
  },
  {
    name: "Peperomia",
    price: 299,
    image: "https://images.unsplash.com/photo-1593691509543-c55fb32d8de5?w=500",
    category: "Indoor",
    tagline: "Compact and endlessly varied",
    description: "Peperomia comes in hundreds of varieties with fascinating textures and patterns. They are compact, slow-growing plants perfect for desks and small spaces. Very forgiving of neglect.",
    sunlight: "Medium indirect light",
    watering: "Once in 10 days",
    temperature: "15°C – 30°C",
    pot_size: "3–4 inch pot",
    difficulty: "Very easy",
    pruning: "Remove dead leaves",
    humidity: "Low to medium (40–50%)",
    pet_safe: "Yes — safe for pets",
    rating: 4.7,
    reviews: 1020
  },
  {
    name: "Begonia",
    price: 349,
    image: "https://images.unsplash.com/photo-1508193638397-1c4234db14d8?w=500",
    category: "Flowering",
    tagline: "Colourful blooms all season long",
    description: "Begonia is a popular flowering plant with beautiful waxy blooms in shades of red, pink, orange, and white. It blooms for months and is perfect for windowsills and balconies.",
    sunlight: "Bright indirect light",
    watering: "Twice a week",
    temperature: "15°C – 28°C",
    pot_size: "6–8 inch pot",
    difficulty: "Easy",
    pruning: "Deadhead spent flowers",
    humidity: "Medium (50–60%)",
    pet_safe: "No — toxic to pets",
    rating: 4.6,
    reviews: 760
  },
  {
    name: "Dieffenbachia",
    price: 449,
    image: "https://images.unsplash.com/photo-1572688484438-313a6e50c333?w=500",
    category: "Indoor",
    tagline: "Bold tropical foliage indoors",
    description: "Dieffenbachia or Dumb Cane has large exotic-looking leaves with beautiful cream and green patterns. It is a fast grower and excellent for filling empty corners with lush tropical foliage.",
    sunlight: "Medium indirect light",
    watering: "Once a week",
    temperature: "16°C – 30°C",
    pot_size: "8–10 inch pot",
    difficulty: "Easy",
    pruning: "Remove lower yellow leaves",
    humidity: "Medium (50–60%)",
    pet_safe: "No — toxic to pets and humans",
    rating: 4.5,
    reviews: 620
  },
  {
    name: "Aglaonema Red",
    price: 549,
    image: "https://images.unsplash.com/photo-1587334274328-64186a80aeee?w=500",
    category: "Air Purifying",
    tagline: "Striking red and green foliage",
    description: "Aglaonema Red is a stunning variety of Chinese Evergreen with brilliantly coloured red and green leaves. It thrives in low light and is one of the most decorative and easy-care indoor plants.",
    sunlight: "Low to medium indirect light",
    watering: "Once a week",
    temperature: "16°C – 30°C",
    pot_size: "6–8 inch pot",
    difficulty: "Easy",
    pruning: "Remove yellow leaves",
    humidity: "Medium (50–60%)",
    pet_safe: "No — toxic to pets",
    rating: 4.8,
    reviews: 940
  },
  {
    name: "Syngonium",
    price: 299,
    image: "https://images.unsplash.com/photo-1612852098516-55d01c75769a?w=500",
    category: "Indoor",
    tagline: "Arrow shaped leaves, endless charm",
    description: "Syngonium or Arrowhead Plant starts as a compact bushy plant and eventually begins to vine. Its arrow-shaped leaves come in shades of green, pink, and white. Very easy to care for.",
    sunlight: "Low to medium indirect light",
    watering: "Once a week",
    temperature: "15°C – 30°C",
    pot_size: "4–6 inch pot",
    difficulty: "Very easy",
    pruning: "Pinch growing tips",
    humidity: "Medium (50–60%)",
    pet_safe: "No — toxic to pets",
    rating: 4.7,
    reviews: 1150
  },
  {
    name: "Marigold",
    price: 99,
    image: "https://images.unsplash.com/photo-1444930694458-01babf71870c?w=500",
    category: "Seasonal",
    tagline: "Sunshine in a flower pot",
    description: "Marigold or Genda Phool is one of the most beloved flowering plants in India. Its bright orange and yellow blooms last for months and naturally repel garden pests. Perfect for balconies.",
    sunlight: "Full direct sunlight",
    watering: "Daily",
    temperature: "15°C – 35°C",
    pot_size: "6–8 inch pot",
    difficulty: "Very easy",
    pruning: "Deadhead regularly",
    humidity: "Low to medium (40–50%)",
    pet_safe: "Yes — safe for pets",
    rating: 4.8,
    reviews: 5600
  },
  {
    name: "Rose",
    price: 399,
    image: "https://images.unsplash.com/photo-1508193638397-1c4234db14d8?w=500",
    category: "Flowering",
    tagline: "Timeless beauty in every petal",
    description: "Roses are the world's most beloved flowers, available in hundreds of varieties and colours. They bloom repeatedly when properly cared for and fill the garden with an unforgettable fragrance.",
    sunlight: "Full direct sunlight",
    watering: "Daily",
    temperature: "15°C – 30°C",
    pot_size: "10–12 inch pot",
    difficulty: "Intermediate",
    pruning: "Prune after each bloom cycle",
    humidity: "Medium (40–60%)",
    pet_safe: "No — thorns present",
    rating: 4.9,
    reviews: 7800
  },
  {
    name: "Jasmine",
    price: 249,
    image: "https://images.unsplash.com/photo-1499028344343-cd173ffc68a9?w=500",
    category: "Flowering",
    tagline: "Fill your evenings with fragrance",
    description: "Jasmine or Mogra is a beloved Indian flowering plant famous for its intensely fragrant white flowers. It blooms prolifically in warm weather and its flowers are used in hair, worship, and perfumes.",
    sunlight: "Full direct sunlight",
    watering: "Daily",
    temperature: "20°C – 35°C",
    pot_size: "8–10 inch pot",
    difficulty: "Easy",
    pruning: "Prune after flowering",
    humidity: "Medium (50–60%)",
    pet_safe: "Yes — safe for pets",
    rating: 4.9,
    reviews: 4200
  },
  {
    name: "Canna Lily",
    price: 299,
    image: "https://images.unsplash.com/photo-1444930694458-01babf71870c?w=500",
    category: "Flowering",
    tagline: "Tropical drama for your garden",
    description: "Canna Lily is a bold tropical plant with large paddle-shaped leaves and spectacular flowers in red, orange, yellow, and pink. It grows rapidly and blooms throughout the warm season.",
    sunlight: "Full direct sunlight",
    watering: "Daily",
    temperature: "20°C – 40°C",
    pot_size: "12–14 inch pot",
    difficulty: "Easy",
    pruning: "Remove spent flower stalks",
    humidity: "Medium (50–60%)",
    pet_safe: "Yes — safe for pets",
    rating: 4.7,
    reviews: 890
  },
  {
    name: "Portulaca",
    price: 149,
    image: "https://images.unsplash.com/photo-1508193638397-1c4234db14d8?w=500",
    category: "Seasonal",
    tagline: "Jewel-bright blooms in harsh sun",
    description: "Portulaca or Moss Rose produces brilliant jewel-toned flowers in almost every colour. It thrives in hot dry conditions and blooms profusely with very little care. Perfect for sunny balconies.",
    sunlight: "Full direct sunlight",
    watering: "Twice a week",
    temperature: "20°C – 40°C",
    pot_size: "4–6 inch pot",
    difficulty: "Very easy",
    pruning: "Minimal required",
    humidity: "Low (30–40%)",
    pet_safe: "Yes — safe for pets",
    rating: 4.7,
    reviews: 1680
  },
  {
    name: "Adenium Obesum",
    price: 799,
    image: "https://images.unsplash.com/photo-1550159930-40066082a4fc?w=500",
    category: "Rare & Exotic",
    tagline: "Rare and exotic succulent tree",
    description: "Adenium Obesum is an exotic succulent with a dramatically swollen trunk called a caudex. It produces stunning trumpet-shaped flowers and develops a unique sculptural form over time.",
    sunlight: "Full direct sunlight",
    watering: "Once a week",
    temperature: "20°C – 40°C",
    pot_size: "8–10 inch pot",
    difficulty: "Intermediate",
    pruning: "Prune sparingly",
    humidity: "Low (30–40%)",
    pet_safe: "No — toxic to pets",
    rating: 4.8,
    reviews: 420
  },
  {
    name: "Fern (Asparagus)",
    price: 299,
    image: "https://images.unsplash.com/photo-1520412099551-62b6bafeb5bb?w=500",
    category: "Ferns & Foliage",
    tagline: "Feathery and graceful indoors",
    description: "Asparagus Fern has delicate feathery fronds that add a soft texture to any space. Despite its name it is not a true fern but a member of the lily family. Great for hanging baskets.",
    sunlight: "Bright indirect light",
    watering: "Twice a week",
    temperature: "15°C – 28°C",
    pot_size: "6–8 inch pot",
    difficulty: "Easy",
    pruning: "Remove yellowing stems",
    humidity: "Medium to high (60–70%)",
    pet_safe: "No — toxic to pets",
    rating: 4.5,
    reviews: 540
  },
  {
    name: "Geranium",
    price: 249,
    image: "https://images.unsplash.com/photo-1499028344343-cd173ffc68a9?w=500",
    category: "Flowering",
    tagline: "Cottage garden charm in a pot",
    description: "Geraniums are classic balcony and window box plants producing cheerful clusters of flowers in red, pink, white, and purple. They are long-blooming and naturally repel mosquitoes.",
    sunlight: "Full direct sunlight",
    watering: "Twice a week",
    temperature: "15°C – 30°C",
    pot_size: "6–8 inch pot",
    difficulty: "Easy",
    pruning: "Deadhead regularly",
    humidity: "Low to medium (40–50%)",
    pet_safe: "No — toxic to pets",
    rating: 4.6,
    reviews: 1230
  },
  {
    name: "Chrysanthemum",
    price: 199,
    image: "https://images.unsplash.com/photo-1508193638397-1c4234db14d8?w=500",
    category: "Seasonal",
    tagline: "Autumn's most cheerful flower",
    description: "Chrysanthemums produce an explosion of flowers in autumn in shades of yellow, white, red, and purple. They are one of the best air purifying plants and symbolise longevity and happiness.",
    sunlight: "Full direct sunlight",
    watering: "Daily",
    temperature: "15°C – 28°C",
    pot_size: "8–10 inch pot",
    difficulty: "Easy",
    pruning: "Pinch tips in summer for bushy growth",
    humidity: "Medium (50–60%)",
    pet_safe: "No — toxic to pets",
    rating: 4.7,
    reviews: 1890
  },
  {
    name: "Lemon Tree (Dwarf)",
    price: 899,
    image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=500",
    category: "Fruiting",
    tagline: "Fresh lemons from your balcony",
    description: "Dwarf Lemon Tree is a compact citrus variety perfect for growing in large pots on balconies. It produces fragrant flowers and real edible lemons. A rewarding and beautiful plant.",
    sunlight: "Full direct sunlight",
    watering: "Daily",
    temperature: "20°C – 40°C",
    pot_size: "14–16 inch pot",
    difficulty: "Intermediate",
    pruning: "Annual shaping recommended",
    humidity: "Medium (50–60%)",
    pet_safe: "No — toxic to pets",
    rating: 4.8,
    reviews: 670
  },
  {
    name: "Tomato Plant",
    price: 149,
    image: "https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?w=500",
    category: "Vegetables",
    tagline: "Grow your own fresh tomatoes",
    description: "Cherry Tomato plant is perfect for balcony gardening, producing clusters of sweet juicy tomatoes in about 60 days. Extremely rewarding for beginner vegetable gardeners.",
    sunlight: "Full direct sunlight",
    watering: "Daily",
    temperature: "20°C – 35°C",
    pot_size: "12–14 inch pot",
    difficulty: "Easy",
    pruning: "Remove suckers regularly",
    humidity: "Medium (50–60%)",
    pet_safe: "No — leaves toxic to pets",
    rating: 4.7,
    reviews: 2400
  },
  {
    name: "Chilli Plant",
    price: 99,
    image: "https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?w=500",
    category: "Vegetables",
    tagline: "Spice up your balcony garden",
    description: "Chilli Plant is a productive and attractive balcony plant that produces colourful chillies in red, green, and yellow. Fresh home-grown chillies have a far superior flavour to store-bought ones.",
    sunlight: "Full direct sunlight",
    watering: "Daily",
    temperature: "20°C – 40°C",
    pot_size: "8–10 inch pot",
    difficulty: "Easy",
    pruning: "Harvest regularly",
    humidity: "Medium (50–60%)",
    pet_safe: "No — irritant to pets",
    rating: 4.8,
    reviews: 3100
  },
  {
    name: "Moringa (Drumstick)",
    price: 249,
    image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=500",
    category: "Herbs & Medicinal",
    tagline: "The most nutritious tree on earth",
    description: "Moringa or Drumstick tree is considered one of the most nutritious plants on earth. Its leaves are packed with vitamins and minerals. Grows rapidly and can be kept compact in large pots.",
    sunlight: "Full direct sunlight",
    watering: "Twice a week",
    temperature: "25°C – 40°C",
    pot_size: "12–14 inch pot",
    difficulty: "Easy",
    pruning: "Prune regularly to maintain height",
    humidity: "Low to medium (40–50%)",
    pet_safe: "Yes — safe for pets",
    rating: 4.8,
    reviews: 1560
  },
  {
    name: "Stevia",
    price: 199,
    image: "https://images.unsplash.com/photo-1628556270448-4d4e4148e1b1?w=500",
    category: "Herbs & Medicinal",
    tagline: "Natural zero calorie sweetener",
    description: "Stevia is a natural sweetener plant whose leaves are 200 times sweeter than sugar with zero calories. A few fresh leaves in tea provide natural sweetness and are beneficial for diabetics.",
    sunlight: "Full to partial sunlight",
    watering: "Daily",
    temperature: "15°C – 30°C",
    pot_size: "6–8 inch pot",
    difficulty: "Easy",
    pruning: "Harvest leaf tips regularly",
    humidity: "Medium (50–60%)",
    pet_safe: "Yes — safe for pets",
    rating: 4.7,
    reviews: 890
  },
  {
    name: "Giloy",
    price: 149,
    image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=500",
    category: "Herbs & Medicinal",
    tagline: "Immunity booster from ancient Ayurveda",
    description: "Giloy or Guduchi is a powerful Ayurvedic herb known for boosting immunity and fighting fever. Its heart-shaped leaves and climbing habit make it an attractive addition to any garden.",
    sunlight: "Partial to full sunlight",
    watering: "Twice a week",
    temperature: "20°C – 40°C",
    pot_size: "8–10 inch pot",
    difficulty: "Easy",
    pruning: "Trim regularly",
    humidity: "Medium (50–60%)",
    pet_safe: "Yes — safe for pets",
    rating: 4.8,
    reviews: 2100
  },
  {
    name: "Ashwagandha",
    price: 199,
    image: "https://images.unsplash.com/photo-1628556270448-4d4e4148e1b1?w=500",
    category: "Herbs & Medicinal",
    tagline: "Ancient adaptogen herb",
    description: "Ashwagandha is one of the most important herbs in Ayurvedic medicine, known for reducing stress and boosting energy. Its roots and leaves have powerful medicinal properties.",
    sunlight: "Full direct sunlight",
    watering: "Twice a week",
    temperature: "20°C – 40°C",
    pot_size: "8–10 inch pot",
    difficulty: "Easy",
    pruning: "Minimal required",
    humidity: "Low (30–40%)",
    pet_safe: "No — toxic to pets in large amounts",
    rating: 4.7,
    reviews: 760
  },
  {
    name: "Brahmi",
    price: 149,
    image: "https://images.unsplash.com/photo-1628556270448-4d4e4148e1b1?w=500",
    category: "Herbs & Medicinal",
    tagline: "Boost memory the natural way",
    description: "Brahmi is a traditional Ayurvedic herb renowned for improving memory, concentration, and reducing anxiety. It is a low-growing creeper that thrives in moist conditions.",
    sunlight: "Partial sunlight",
    watering: "Daily — loves moisture",
    temperature: "15°C – 30°C",
    pot_size: "6–8 inch pot",
    difficulty: "Easy",
    pruning: "Trim regularly",
    humidity: "High (60–80%)",
    pet_safe: "Yes — safe for pets",
    rating: 4.6,
    reviews: 580
  },
  {
    name: "Lemongrass",
    price: 149,
    image: "https://images.unsplash.com/photo-1628556270448-4d4e4148e1b1?w=500",
    category: "Herbs & Medicinal",
    tagline: "Citrusy fragrance and great health",
    description: "Lemongrass is a fragrant tropical grass used extensively in cooking and herbal teas. It naturally repels mosquitoes and has anti-inflammatory and digestive benefits.",
    sunlight: "Full direct sunlight",
    watering: "Twice a week",
    temperature: "20°C – 40°C",
    pot_size: "8–10 inch pot",
    difficulty: "Very easy",
    pruning: "Harvest outer stalks",
    humidity: "Medium (50–60%)",
    pet_safe: "No — toxic to pets",
    rating: 4.8,
    reviews: 1890
  },
  {
    name: "Pandan",
    price: 199,
    image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=500",
    category: "Herbs & Medicinal",
    tagline: "Fragrant leaves for cooking and health",
    description: "Pandan or Screwpine produces long fragrant leaves used extensively in South and Southeast Asian cooking. It has a unique vanilla-like scent and is used in rice dishes and desserts.",
    sunlight: "Partial to full sunlight",
    watering: "Twice a week",
    temperature: "20°C – 35°C",
    pot_size: "8–10 inch pot",
    difficulty: "Easy",
    pruning: "Harvest outer leaves",
    humidity: "Medium to high (60–70%)",
    pet_safe: "Yes — safe for pets",
    rating: 4.6,
    reviews: 430
  },
  {
    name: "Nerve Plant (Fittonia)",
    price: 349,
    image: "https://images.unsplash.com/photo-1587334274328-64186a80aeee?w=500",
    category: "Ferns & Foliage",
    tagline: "Living mosaic of veined leaves",
    description: "Nerve Plant or Fittonia has strikingly beautiful leaves with a network of white, pink, or red veins. It is perfect for terrariums and tabletop displays and loves high humidity.",
    sunlight: "Low to medium indirect light",
    watering: "Twice a week",
    temperature: "16°C – 28°C",
    pot_size: "3–4 inch pot",
    difficulty: "Intermediate",
    pruning: "Pinch tips for fullness",
    humidity: "High (60–80%)",
    pet_safe: "Yes — safe for pets",
    rating: 4.6,
    reviews: 620
  },
  {
    name: "Air Plant (Tillandsia)",
    price: 399,
    image: "https://images.unsplash.com/photo-1550159930-40066082a4fc?w=500",
    category: "Rare & Exotic",
    tagline: "No soil needed — truly unique",
    description: "Air Plants or Tillandsias are unique plants that grow without soil, absorbing moisture and nutrients through their leaves. They can be displayed in glass terrariums, on driftwood, or shells.",
    sunlight: "Bright indirect light",
    watering: "Mist 2–3 times a week",
    temperature: "15°C – 32°C",
    pot_size: "No pot needed",
    difficulty: "Easy",
    pruning: "Remove dead outer leaves",
    humidity: "Medium to high (50–70%)",
    pet_safe: "Yes — safe for pets",
    rating: 4.7,
    reviews: 840
  },
  {
    name: "Monstera Adansonii",
    price: 799,
    image: "https://images.unsplash.com/photo-1614594975525-e45190c55d0b?w=500",
    category: "Climbers",
    tagline: "Swiss cheese plant with holey leaves",
    description: "Monstera Adansonii or Swiss Cheese Plant has uniquely perforated leaves that make it one of the most photogenic houseplants. It is a fast grower and perfect for trailing or climbing.",
    sunlight: "Bright indirect light",
    watering: "Once a week",
    temperature: "18°C – 30°C",
    pot_size: "6–8 inch pot",
    difficulty: "Easy",
    pruning: "Trim to control growth",
    humidity: "High (60–80%)",
    pet_safe: "No — toxic to pets",
    rating: 4.8,
    reviews: 1120
  },
  {
    name: "Alocasia",
    price: 899,
    image: "https://images.unsplash.com/photo-1614594975525-e45190c55d0b?w=500",
    category: "Palms & Tropicals",
    tagline: "Elephant ears of the plant world",
    description: "Alocasia or Elephant Ear plant has dramatic large arrow-shaped leaves with prominent veins. It creates a bold tropical statement and is highly sought after by plant collectors.",
    sunlight: "Bright indirect light",
    watering: "Once a week",
    temperature: "18°C – 30°C",
    pot_size: "10–12 inch pot",
    difficulty: "Intermediate",
    pruning: "Remove dead leaves at base",
    humidity: "High (60–80%)",
    pet_safe: "No — toxic to pets",
    rating: 4.7,
    reviews: 680
  },
  {
    name: "Pilea Peperomioides",
    price: 499,
    image: "https://images.unsplash.com/photo-1593691509543-c55fb32d8de5?w=500",
    category: "Indoor",
    tagline: "The trendy Chinese money plant",
    description: "Pilea Peperomioides or Chinese Money Plant has charming round pancake-shaped leaves on long stems. It is a trendy Instagram favourite and readily produces offshoots to share with friends.",
    sunlight: "Bright indirect light",
    watering: "Once a week",
    temperature: "13°C – 30°C",
    pot_size: "4–6 inch pot",
    difficulty: "Easy",
    pruning: "Remove offshoots or pot separately",
    humidity: "Medium (40–60%)",
    pet_safe: "Yes — safe for pets",
    rating: 4.8,
    reviews: 970
  },
  {
    name: "Maranta (Prayer Plant)",
    price: 449,
    image: "https://images.unsplash.com/photo-1612852098516-55d01c75769a?w=500",
    category: "Ferns & Foliage",
    tagline: "Leaves that pray at night",
    description: "Maranta or Prayer Plant has beautifully patterned leaves that fold upward at night like hands in prayer. It is a stunning low-light plant with intricate herringbone patterns on its leaves.",
    sunlight: "Low to medium indirect light",
    watering: "Twice a week",
    temperature: "16°C – 28°C",
    pot_size: "4–6 inch pot",
    difficulty: "Intermediate",
    pruning: "Remove damaged leaves",
    humidity: "High (60–80%)",
    pet_safe: "Yes — safe for pets",
    rating: 4.7,
    reviews: 750
  },
  {
    name: "Stapelia",
    price: 349,
    image: "https://images.unsplash.com/photo-1459411621453-7b03977f4bfc?w=500",
    category: "Succulents",
    tagline: "Star shaped flowers from a cactus-like plant",
    description: "Stapelia is a fascinating leafless succulent that produces large star-shaped flowers with intricate patterns. It is drought tolerant and perfect for sunny windowsills.",
    sunlight: "Bright direct light",
    watering: "Once in 3 weeks",
    temperature: "15°C – 35°C",
    pot_size: "4–6 inch pot",
    difficulty: "Easy",
    pruning: "Minimal required",
    humidity: "Low (20–30%)",
    pet_safe: "Yes — safe for pets",
    rating: 4.5,
    reviews: 310
  },
  {
    name: "Sedum",
    price: 199,
    image: "https://images.unsplash.com/photo-1550159930-40066082a4fc?w=500",
    category: "Succulents",
    tagline: "Carpet of tiny succulent rosettes",
    description: "Sedum is a diverse group of succulents ranging from ground-hugging carpets to upright plants with star-shaped flowers. They are incredibly tough and drought-resistant.",
    sunlight: "Bright direct light",
    watering: "Once in 2 weeks",
    temperature: "10°C – 35°C",
    pot_size: "3–6 inch pot",
    difficulty: "Very easy",
    pruning: "Remove dead growth",
    humidity: "Low (20–40%)",
    pet_safe: "Yes — safe for pets",
    rating: 4.6,
    reviews: 780
  },
  {
    name: "Gasteria",
    price: 249,
    image: "https://images.unsplash.com/photo-1459411621453-7b03977f4bfc?w=500",
    category: "Succulents",
    tagline: "The tough aloe relative",
    description: "Gasteria is a tough low-maintenance succulent related to Aloe. It has thick tongue-shaped leaves often with white spots. It is one of the few succulents that tolerates shade.",
    sunlight: "Low to medium indirect light",
    watering: "Once in 2–3 weeks",
    temperature: "10°C – 35°C",
    pot_size: "4–6 inch pot",
    difficulty: "Very easy",
    pruning: "Remove dead outer leaves",
    humidity: "Low (30–40%)",
    pet_safe: "Yes — safe for pets",
    rating: 4.6,
    reviews: 420
  },
  {
    name: "Lithops (Living Stones)",
    price: 499,
    image: "https://images.unsplash.com/photo-1459411621453-7b03977f4bfc?w=500",
    category: "Rare & Exotic",
    tagline: "Plants disguised as pebbles",
    description: "Lithops or Living Stones are extraordinary succulents that mimic pebbles in their natural desert habitat. They are one of the most unique and conversation-starting plants available.",
    sunlight: "Bright direct sunlight",
    watering: "Once in 4–6 weeks",
    temperature: "15°C – 35°C",
    pot_size: "3–4 inch pot",
    difficulty: "Intermediate",
    pruning: "Not required",
    humidity: "Very low (20–30%)",
    pet_safe: "Yes — safe for pets",
    rating: 4.8,
    reviews: 560
  },
  {
    name: "Crassula Ovata",
    price: 299,
    image: "https://images.unsplash.com/photo-1509423350716-97f9360b4e09?w=500",
    category: "Succulents",
    tagline: "Classic money tree succulent",
    description: "Crassula Ovata or Jade Plant is a classic succulent with thick glossy oval leaves that develops a beautiful tree-like form over time. It is considered a symbol of good fortune.",
    sunlight: "Bright direct or indirect light",
    watering: "Once in 2 weeks",
    temperature: "15°C – 30°C",
    pot_size: "4–8 inch pot",
    difficulty: "Easy",
    pruning: "Trim for desired shape",
    humidity: "Low (30–40%)",
    pet_safe: "No — toxic to pets",
    rating: 4.7,
    reviews: 890
  },
  {
    name: "Euphorbia (Crown of Thorns)",
    price: 349,
    image: "https://images.unsplash.com/photo-1459411621453-7b03977f4bfc?w=500",
    category: "Outdoor",
    tagline: "Thorny beauty that blooms non-stop",
    description: "Crown of Thorns is a drought-tolerant succulent shrub that blooms almost continuously in warm weather. Its small bright flowers appear year round making it one of the most long-blooming plants.",
    sunlight: "Full direct sunlight",
    watering: "Once in 2 weeks",
    temperature: "15°C – 40°C",
    pot_size: "6–8 inch pot",
    difficulty: "Easy",
    pruning: "Minimal — wear gloves",
    humidity: "Low (30–40%)",
    pet_safe: "No — toxic and thorny",
    rating: 4.6,
    reviews: 640
  },
  {
    name: "Plumeria (Frangipani)",
    price: 599,
    image: "https://images.unsplash.com/photo-1508193638397-1c4234db14d8?w=500",
    category: "Flowering",
    tagline: "Tropical fragrance in full bloom",
    description: "Plumeria or Frangipani produces exquisite fragrant flowers in white, yellow, pink, and red. It is widely used in garlands and has a heavenly scent. Drops leaves in winter and regrows in spring.",
    sunlight: "Full direct sunlight",
    watering: "Once a week",
    temperature: "20°C – 40°C",
    pot_size: "12–14 inch pot",
    difficulty: "Easy",
    pruning: "Prune after dormancy",
    humidity: "Low to medium (40–50%)",
    pet_safe: "No — toxic to pets",
    rating: 4.9,
    reviews: 1340
  },
  {
    name: "Ixora",
    price: 249,
    image: "https://images.unsplash.com/photo-1444930694458-01babf71870c?w=500",
    category: "Flowering",
    tagline: "Clusters of tiny vivid flowers",
    description: "Ixora produces dense clusters of small star-shaped flowers in brilliant red, orange, pink, and yellow. It blooms throughout the year in tropical climates and is a favourite garden shrub in India.",
    sunlight: "Full direct sunlight",
    watering: "Daily",
    temperature: "20°C – 35°C",
    pot_size: "8–10 inch pot",
    difficulty: "Easy",
    pruning: "Trim after flowering",
    humidity: "Medium (50–60%)",
    pet_safe: "Yes — safe for pets",
    rating: 4.7,
    reviews: 1120
  },
  {
    name: "Heliconia",
    price: 799,
    image: "https://images.unsplash.com/photo-1444930694458-01babf71870c?w=500",
    category: "Palms & Tropicals",
    tagline: "Lobster claw tropical showstopper",
    description: "Heliconia produces extraordinarily dramatic lobster claw shaped flower bracts in vivid shades of red, orange, and yellow. It is a true tropical showstopper for large garden spaces.",
    sunlight: "Full direct sunlight",
    watering: "Daily",
    temperature: "22°C – 40°C",
    pot_size: "14–16 inch pot",
    difficulty: "Intermediate",
    pruning: "Remove spent flower stalks",
    humidity: "High (70–80%)",
    pet_safe: "Yes — safe for pets",
    rating: 4.8,
    reviews: 280
  },
  {
    name: "Dianthus (Carnation)",
    price: 199,
    image: "https://images.unsplash.com/photo-1508193638397-1c4234db14d8?w=500",
    category: "Seasonal",
    tagline: "Frilly flowers with a spicy clove scent",
    description: "Dianthus or Carnation produces charming frilly flowers in pink, red, white, and bicolour with a lovely spicy clove fragrance. Perfect for winter and spring balcony gardens in India.",
    sunlight: "Full direct sunlight",
    watering: "Twice a week",
    temperature: "10°C – 25°C",
    pot_size: "6–8 inch pot",
    difficulty: "Easy",
    pruning: "Deadhead regularly",
    humidity: "Medium (40–60%)",
    pet_safe: "No — toxic to pets",
    rating: 4.6,
    reviews: 960
  },
  {
    name: "Torenia (Wishbone Flower)",
    price: 149,
    image: "https://images.unsplash.com/photo-1508193638397-1c4234db14d8?w=500",
    category: "Seasonal",
    tagline: "Shade loving flowering gem",
    description: "Torenia or Wishbone Flower is a delightful annual that thrives in partial shade, producing trumpet-shaped flowers in purple, pink, and white. Perfect for shaded balconies.",
    sunlight: "Partial shade",
    watering: "Daily",
    temperature: "15°C – 30°C",
    pot_size: "6–8 inch pot",
    difficulty: "Easy",
    pruning: "Pinch tips for bushiness",
    humidity: "Medium to high (60–70%)",
    pet_safe: "Yes — safe for pets",
    rating: 4.5,
    reviews: 380
  },
  {
    name: "Cactus (Moon)",
    price: 299,
    image: "https://images.unsplash.com/photo-1459411621453-7b03977f4bfc?w=500",
    category: "Cactus",
    tagline: "Colourful grafted cactus ball",
    description: "Moon Cactus is a brightly coloured grafted cactus featuring a vivid red, yellow, or orange ball on top of a green base cactus. A quirky and eye-catching desktop ornament.",
    sunlight: "Bright indirect light",
    watering: "Once in 3 weeks",
    temperature: "15°C – 35°C",
    pot_size: "3–4 inch pot",
    difficulty: "Easy",
    pruning: "Not required",
    humidity: "Low (20–30%)",
    pet_safe: "No — sharp spines",
    rating: 4.7,
    reviews: 1240
  },
  {
    name: "Burro's Tail",
    price: 399,
    image: "https://images.unsplash.com/photo-1550159930-40066082a4fc?w=500",
    category: "Hanging",
    tagline: "Cascading tails of blue-green beads",
    description: "Burro's Tail or Sedum Morganianum is a stunning trailing succulent with long stems densely packed with plump blue-green leaves. It looks spectacular in hanging pots.",
    sunlight: "Bright indirect light",
    watering: "Once in 2–3 weeks",
    temperature: "15°C – 30°C",
    pot_size: "4–6 inch hanging pot",
    difficulty: "Easy",
    pruning: "Remove dead stems",
    humidity: "Low (30–40%)",
    pet_safe: "Yes — safe for pets",
    rating: 4.7,
    reviews: 580
  },
  {
    name: "Sansevieria Cylindrica",
    price: 449,
    image: "https://images.unsplash.com/photo-1593691509543-c55fb32d8de5?w=500",
    category: "Air Purifying",
    tagline: "Architectural cylindrical leaves",
    description: "Sansevieria Cylindrica has striking cylindrical leaves that grow in a fan arrangement. It is as tough as the regular snake plant with a more modern architectural look.",
    sunlight: "Low to bright indirect light",
    watering: "Once in 2–3 weeks",
    temperature: "15°C – 35°C",
    pot_size: "4–6 inch pot",
    difficulty: "Very easy",
    pruning: "Remove dead leaves",
    humidity: "Low (30–50%)",
    pet_safe: "No — toxic to pets",
    rating: 4.7,
    reviews: 670
  },
  {
    name: "Columnea (Goldfish Plant)",
    price: 549,
    image: "https://images.unsplash.com/photo-1508193638397-1c4234db14d8?w=500",
    category: "Hanging",
    tagline: "Tiny orange fish swimming in leaves",
    description: "Goldfish Plant produces an abundance of bright orange tubular flowers that resemble leaping goldfish among its glossy dark green leaves. A delightful and unusual flowering houseplant.",
    sunlight: "Bright indirect light",
    watering: "Once a week",
    temperature: "16°C – 28°C",
    pot_size: "6–8 inch hanging pot",
    difficulty: "Intermediate",
    pruning: "Trim after flowering",
    humidity: "High (60–80%)",
    pet_safe: "Yes — safe for pets",
    rating: 4.6,
    reviews: 290
  },
  {
    name: "Clivia",
    price: 699,
    image: "https://images.unsplash.com/photo-1508193638397-1c4234db14d8?w=500",
    category: "Flowering",
    tagline: "Spectacular orange indoor blooms",
    description: "Clivia produces spectacular clusters of trumpet-shaped orange flowers above strap-like dark green leaves. It is a slow-growing long-lived plant that thrives in low light conditions.",
    sunlight: "Low to medium indirect light",
    watering: "Once a week",
    temperature: "10°C – 28°C",
    pot_size: "8–10 inch pot",
    difficulty: "Easy",
    pruning: "Remove spent flower stalks",
    humidity: "Medium (40–60%)",
    pet_safe: "No — toxic to pets",
    rating: 4.7,
    reviews: 340
  },
  {
    name: "Bromeliaid",
    price: 599,
    image: "https://images.unsplash.com/photo-1599598425947-5202edd56fde?w=500",
    category: "Palms & Tropicals",
    tagline: "Exotic tropical colour indoors",
    description: "Bromeliads are exotic tropical plants with stunning rosettes of colourful leaves and a central flower spike. They are extremely long-lasting and add a dramatic tropical feel to any interior.",
    sunlight: "Bright indirect light",
    watering: "Fill central cup with water",
    temperature: "18°C – 30°C",
    pot_size: "6–8 inch pot",
    difficulty: "Easy",
    pruning: "Remove pups and repot",
    humidity: "High (60–70%)",
    pet_safe: "Yes — safe for pets",
    rating: 4.7,
    reviews: 450
  },
  {
    name: "Pitcher Plant",
    price: 799,
    image: "https://images.unsplash.com/photo-1550159930-40066082a4fc?w=500",
    category: "Rare & Exotic",
    tagline: "Nature's own insect trap",
    description: "Pitcher Plant is a fascinating carnivorous plant that traps and digests insects in its pitcher-shaped leaves. It is a unique and conversation-starting addition to any collection.",
    sunlight: "Bright indirect light",
    watering: "Keep in tray of distilled water",
    temperature: "18°C – 30°C",
    pot_size: "6–8 inch pot",
    difficulty: "Intermediate",
    pruning: "Remove dead pitchers",
    humidity: "High (70–80%)",
    pet_safe: "Yes — safe for pets",
    rating: 4.8,
    reviews: 380
  },
  {
    name: "Venus Fly Trap",
    price: 699,
    image: "https://images.unsplash.com/photo-1550159930-40066082a4fc?w=500",
    category: "Rare & Exotic",
    tagline: "The most famous carnivorous plant",
    description: "Venus Fly Trap is the world's most famous carnivorous plant. Its hinged jaw-like leaves snap shut around insects. A fascinating and educational plant loved by children and adults alike.",
    sunlight: "Bright direct sunlight",
    watering: "Keep in tray of distilled water",
    temperature: "15°C – 35°C",
    pot_size: "4–6 inch pot",
    difficulty: "Intermediate",
    pruning: "Remove dead traps",
    humidity: "High (70–80%)",
    pet_safe: "Yes — safe for pets",
    rating: 4.9,
    reviews: 920
  },
  {
    name: "Bamboo Palm",
    price: 999,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500",
    category: "Palms & Tropicals",
    tagline: "Elegant multi-stemmed indoor palm",
    description: "Bamboo Palm is a graceful multi-stemmed palm with elegant arching fronds. It is one of the top rated air purifying plants by NASA and creates a lush tropical atmosphere indoors.",
    sunlight: "Bright indirect light",
    watering: "Twice a week",
    temperature: "16°C – 32°C",
    pot_size: "12–14 inch pot",
    difficulty: "Easy",
    pruning: "Remove yellow fronds",
    humidity: "Medium to high (50–70%)",
    pet_safe: "Yes — safe for pets",
    rating: 4.7,
    reviews: 560
  },
  {
    name: "Dwarf Umbrella Tree",
    price: 649,
    image: "https://images.unsplash.com/photo-1572688484438-313a6e50c333?w=500",
    category: "Indoor",
    tagline: "Compact tropical tree indoors",
    description: "Dwarf Umbrella Tree or Schefflera Arboricola is a compact version of the umbrella tree with smaller leaflets arranged in circular patterns. It is perfect for desks and medium-sized spaces.",
    sunlight: "Medium to bright indirect light",
    watering: "Once a week",
    temperature: "15°C – 30°C",
    pot_size: "6–8 inch pot",
    difficulty: "Easy",
    pruning: "Trim to desired shape",
    humidity: "Medium (40–60%)",
    pet_safe: "No — toxic to pets",
    rating: 4.5,
    reviews: 430
  },
  {
    name: "Ornamental Banana",
    price: 1199,
    image: "https://images.unsplash.com/photo-1614594975525-e45190c55d0b?w=500",
    category: "Palms & Tropicals",
    tagline: "Instant tropical paradise",
    description: "Ornamental Banana plant has enormous paddle-shaped leaves that create an instant tropical paradise. While it may produce small ornamental fruits, it is primarily grown for its dramatic foliage.",
    sunlight: "Full direct sunlight",
    watering: "Daily",
    temperature: "22°C – 40°C",
    pot_size: "16–18 inch pot",
    difficulty: "Easy",
    pruning: "Remove dead lower leaves",
    humidity: "High (60–80%)",
    pet_safe: "Yes — safe for pets",
    rating: 4.7,
    reviews: 320
  },
  {
    name: "Night Blooming Jasmine",
    price: 299,
    image: "https://images.unsplash.com/photo-1499028344343-cd173ffc68a9?w=500",
    category: "Flowering",
    tagline: "Fill nights with heavenly fragrance",
    description: "Night Blooming Jasmine or Raat Ki Rani produces tiny white flowers that release an intensely sweet fragrance after sunset. One plant can perfume an entire neighbourhood on warm evenings.",
    sunlight: "Full to partial sunlight",
    watering: "Twice a week",
    temperature: "20°C – 38°C",
    pot_size: "10–12 inch pot",
    difficulty: "Easy",
    pruning: "Prune after heavy blooming",
    humidity: "Medium (50–60%)",
    pet_safe: "No — toxic to pets",
    rating: 4.9,
    reviews: 2800
  },
  {
    name: "Parijat (Night Jasmine)",
    price: 349,
    image: "https://images.unsplash.com/photo-1499028344343-cd173ffc68a9?w=500",
    category: "Flowering",
    tagline: "Sacred tree with divine fragrance",
    description: "Parijat or Harsingar is a sacred flowering tree in Hindu mythology. Its delicate white flowers with orange stems fall to the ground at dawn creating a fragrant carpet of blossoms.",
    sunlight: "Full direct sunlight",
    watering: "Twice a week",
    temperature: "20°C – 38°C",
    pot_size: "12–14 inch pot",
    difficulty: "Easy",
    pruning: "Prune annually",
    humidity: "Medium (50–60%)",
    pet_safe: "Yes — safe for pets",
    rating: 4.9,
    reviews: 1560
  }
];

const seedPlants = async () => {
  try {
    console.log('🌱 Seeding 100 plants into database...');
    for (const plant of plants) {
      await pool.query(
        `INSERT INTO products (name, price, image, category, tagline, description,
        sunlight, watering, temperature, pot_size, difficulty, pruning, humidity,
        pet_safe, rating, reviews) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16)`,
        [plant.name, plant.price, plant.image, plant.category, plant.tagline,
          plant.description, plant.sunlight, plant.watering, plant.temperature,
          plant.pot_size, plant.difficulty, plant.pruning, plant.humidity,
          plant.pet_safe, plant.rating, plant.reviews]
      );
    }
    console.log(`✅ Successfully seeded ${plants.length} plants!`);
    process.exit(0);
  } catch (err) {
    console.error('❌ Seeding failed:', err.message);
    process.exit(1);
  }
};

seedPlants();